### Test logowania (Poprawne dane)
POST http://localhost:8080/api/auth/login?username=lab_olsztyn&password=SuperTajneHaslo123

### Test logowania (BŁĘDNE HASŁO)
POST http://localhost:8080/api/auth/login?username=lab_olsztyn&password=zle_haslo_123