# Port, na którym uruchomi si? serwer (domy?lnie 8080)
server.port=8080

# Adres bazy danych
spring.datasource.url=jdbc:mariadb://localhost:3306/medicalytics

# Login do MariaDB
spring.datasource.username=root

# Twoje has?o do MariaDB (wpisz tu swoje rzeczywiste has?o!)
spring.datasource.password=szymonmatcha69

# Sterownik MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Pozwala Springowi automatycznie zaktualizowa? tabel? w bazie na podstawie klasy User
spring.jpa.hibernate.ddl-auto=update

# Pokazuje w konsoli zapytania SQL, które Spring wykonuje w tle
spring.jpa.show-sql=true